


## Database Properties for MySQL

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecomapp
    username: root
    password: password

  jpa:
    generate-ddl: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/